authors:
  waverlyofoz:
    name: waverlyofoz
    description: waverlyofoz
    avatar: https://0.gravatar.com/avatar/7b4ef598995df73a7ad212d939f740b8baff2699fb021ae1d668b191039b5f7e?size=256
    slug: waverlyofoz
    url: https://waverlyofoz.github.io